### ISSUE TITLE
Can't set headers after they're sent

### ISSUE THREAD

**Issue by ServCinc** [ServCinc/priority1auction#1]
Error Output:
auction-4 (err): Error: Can't set headers after they are sent.
auction-4 (err):     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
auction-4 (err):     at ServerResponse.header (/srv/node_apps/priority1auction/node_modules/express/lib/response.js:718:10)
auction-4 (err):     at ServerResponse.send (/srv/node_apps/priority1auction/node_modules/express/lib/response.js:163:12)
auction-4 (err):     at ServerResponse.json (/srv/node_apps/priority1auction/node_modules/express/lib/response.js:249:15)
auction-4 (err):     at ServerResponse.send (/srv/node_apps/priority1auction/node_modules/express/lib/response.js:151:21)
auction-4 (err):     at /srv/node_apps/priority1auction/routes/pages.js:83:55
auction-4 (err):     at model.<anonymous> (/srv/node_apps/priority1auction/node_modules/mongoose/lib/document.js:1894:20)
auction-4 (err):     at next_ (/srv/node_apps/priority1auction/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:89:34)
auction-4 (err):     at fnWrapper (/srv/node_apps/priority1auction/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:186:18)
auction-4 (err):     at /srv/node_apps/priority1auction/node_modules/mongoose/lib/model.js:3343:16
auction-4 (err):     at /srv/node_apps/priority1auction/node_modules/mongoose/lib/model.js:228:5
auction-4 (err):     at /srv/node_apps/priority1auction/node_modules/mongoose/lib/model.js:166:9
auction-4 (err):     at handleCallback (/srv/node_apps/priority1auction/node_modules/mongoose/node_modules/mongodb/lib/utils.js:96:12)
auction-4 (err):     at /srv/node_apps/priority1auction/node_modules/mongoose/node_modules/mongodb/lib/collection.js:1010:5
auction-4 (err):     at commandCallback (/srv/node_apps/priority1auction/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1194:9)
auction-4 (err):     at Callbacks.emit (/srv/node_apps/priority1auction/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
auction-4 (err): 2016-06-23 13:11 -04:00: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
auction-4 (err): 2016-06-23 13:48 -04:00: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
auction-4 (err): 2016-06-24 11:47 -04:00: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html

**Comment by ServCinc** [comment]
Fixed in commit 47cb9d9. Multiple headers were being set so simplfied the loops.
